[build]
  publish = "static"
  command = "python -m pip install --upgrade pip && pip install -r netlify/functions/requirements.txt"

[functions]
  runtime = "python3.9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200