[build]
  publish = "static"
  command = "pip install -r netlify/functions/requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.10"

[functions]
  directory = "netlify/functions"
  node_bundler = "none"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200