[build]
  publish = "."
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt && cp _redirects static/"

[build.environment]
  PYTHON_VERSION = "3.11.13"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200