[build]
  publish = "static"
  command = "pip install -r requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.11"

[functions]
  directory = "netlify/functions"

[functions.app]
  included_files = ["**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200