[build]
  publish = "static"
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"